#!/bin/bash
# =============================================================================
# Generates the self-signed TLS certificate embedded in the garage door
# firmware, and writes it out as a C header.
#
# Run this ONCE. The certificate is valid for 10 years, so there is no renewal
# to schedule and no ACME client on the device.
#
# Browsers will show a warning for a self-signed certificate. Two ways around
# that: click through it, or install cert.pem on the device as a trusted
# certificate (Android: Settings > Security > Encryption & credentials >
# Install a certificate > CA certificate), after which there is no warning.
#
# The Android app pins this exact certificate, so it never sees a warning and
# is arguably better protected than normal HTTPS - it trusts precisely one
# certificate rather than every CA in the world.
#
# Usage:  ./make-cert.sh
# Output: cert.pem, key.pem, components/web_server_idf/cert.h
# =============================================================================

set -e

# Every name and address the device is reached by must be listed here, or the
# certificate won't match and clients will complain about more than just it
# being self-signed.
# Read from cert-config if present, otherwise prompt. Keeping these out of the
# script means the script itself can be published unchanged.
CONFIG_FILE="$(dirname "$0")/cert-config"

if [ -f "$CONFIG_FILE" ]; then
    # shellcheck source=/dev/null
    . "$CONFIG_FILE"
fi

if [ -z "$LOCAL_IP" ]; then
    read -rp "Device's local IP address (e.g. 192.168.1.50): " LOCAL_IP
fi
if [ -z "$PUBLIC_HOST" ]; then
    read -rp "Public hostname, or press Enter for none (e.g. you.duckdns.org): " PUBLIC_HOST
fi

DAYS="${DAYS:-3650}"

OUT_DIR="$(dirname "$0")"
cd "$OUT_DIR"

echo "Generating a 10-year self-signed certificate..."
echo "  Local IP:    $LOCAL_IP"
echo "  Public name: ${PUBLIC_HOST:-(none)}"
echo

# 2048-bit RSA rather than 4096: the handshake is CPU work on a 240MHz chip,
# and 4096-bit roughly quadruples it for no meaningful gain here.
if [ -n "$PUBLIC_HOST" ]; then
    SAN="DNS:$PUBLIC_HOST,IP:$LOCAL_IP"
    SUBJECT_CN="$PUBLIC_HOST"
else
    SAN="IP:$LOCAL_IP"
    SUBJECT_CN="$LOCAL_IP"
fi

openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout key.pem -out cert.pem -days "$DAYS" \
  -subj "/CN=$SUBJECT_CN/O=ESPHome Device" \
  -addext "subjectAltName=$SAN" \
  -addext "basicConstraints=critical,CA:FALSE" \
  -addext "keyUsage=critical,digitalSignature,keyEncipherment" \
  -addext "extendedKeyUsage=serverAuth"

echo
echo "Writing components/web_server_idf/cert.h ..."

mkdir -p components/web_server_idf

{
  echo "#pragma once"
  echo "// GENERATED by make-cert.sh - do not edit by hand."
  echo "// Self-signed certificate embedded in the firmware. Valid 10 years."
  echo "// Regenerate with ./make-cert.sh, then reflash AND update the pin in the"
  echo "// Android app (see CERT_SHA256 below)."
  echo
  echo "static const char GARAGE_SERVER_CERT_PEM[] ="
  sed 's/.*/  "&\\n"/' cert.pem
  echo ";"
  echo
  echo "static const char GARAGE_SERVER_KEY_PEM[] ="
  sed 's/.*/  "&\\n"/' key.pem
  echo ";"
} > components/web_server_idf/cert.h

echo
echo "Done."
echo
echo "SHA-256 fingerprint (needed for certificate pinning in the Android app):"
openssl x509 -in cert.pem -noout -fingerprint -sha256

echo
echo "Base64 of the SHA-256 public key hash (this is the value the app pins):"
openssl x509 -in cert.pem -pubkey -noout \
  | openssl pkey -pubin -outform der \
  | openssl dgst -sha256 -binary \
  | openssl enc -base64

echo
echo "key.pem is the PRIVATE key. Do not share it or commit it anywhere public."
